# Generated by Django 5.1.4 on 2025-06-30 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0006_player_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ItemsBD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('can_register', models.BooleanField(default=False)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('ball', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.ball')),
                ('special', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.special')),
            ],
            options={
                'db_table': 'items',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemsInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.itemsbd')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_models.player')),
            ],
            options={
                'db_table': 'itemsinstance',
                'managed': True,
            },
        ),
    ]
