# Generated by Django 5.1.4 on 2025-06-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0007_alter_ball_options_alter_ballinstance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guildconfig',
            name='items',
            field=models.ManyToManyField(default=list, to='bd_models.itemsbd'),
        ),
        migrations.AddField(
            model_name='itemsbd',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
