# Generated by Django 5.1.4 on 2025-07-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0008_alter_ball_options_alter_ballinstance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cooldown',
            field=models.DateTimeField(null=True),
        ),
    ]
