# Generated by Django 5.1.4 on 2025-07-02 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0009_alter_ball_options_alter_ballinstance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ball',
            options={'managed': True, 'verbose_name': 'hispanicball', 'verbose_name_plural': 'hispanicballs'},
        ),
        migrations.AlterModelOptions(
            name='ballinstance',
            options={'managed': True, 'verbose_name': 'hispanicball instance'},
        ),
        migrations.AlterModelOptions(
            name='itemsbd',
            options={'managed': True, 'verbose_name': 'item', 'verbose_name_plural': 'items'},
        ),
        migrations.AddField(
            model_name='guildconfig',
            name='update_items',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemsbd',
            name='emoji_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ball',
            name='country',
            field=models.CharField(max_length=48, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='itemsbd',
            name='ball',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.ball'),
        ),
        migrations.AlterField(
            model_name='itemsbd',
            name='special',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bd_models.special'),
        ),
    ]
