# Generated by Django 5.1.4 on 2025-07-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_models', '0011_player_trade_cooldown_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ball',
            options={'managed': True, 'verbose_name': 'countryball', 'verbose_name_plural': 'countryballs'},
        ),
        migrations.AlterModelOptions(
            name='ballinstance',
            options={'managed': True, 'verbose_name': 'countryball instance'},
        ),
        migrations.AddField(
            model_name='itemsbd',
            name='end_date',
            field=models.DateTimeField(default=None, help_text='End time of the event. If blank, the event is permanent', null=True),
        ),
        migrations.AddField(
            model_name='itemsbd',
            name='start_date',
            field=models.DateTimeField(default=None, help_text='Start time of the item. If blank, starts immediately', null=True),
        ),
    ]
